### ISSUE TITLE
New feature Request: Sound Notification

### ISSUE THREAD

**Issue by xuli500177** [ofekmiz/Habitica-Pomodoro-SiteKeeper#10]
Thanks for your update! This extension is working well on my computer now!

However, there is small feedback: Whether it is possible to add a notification sound when the pom ran over? Sometimes I am focusing on my book rather than the screen, so I won't know the pom time is out without a sound alert. How about an app notification like Break Extension Start alert? Or a sound notice in Chrome?

Anyhow, this is one of the most excellent Chrome Extension I've ever used! Thank you😁

**Comment by ofekmiz** [comment]
Added Sound notifications! will be available in the next update
