### ISSUE TITLE
Audio Feature Suggestion

### ISSUE THREAD

**Issue by dknestaut** [ofekmiz/Habitica-Pomodoro-SiteKeeper#11]
I like the extension, but sometimes I'm not looking at my computer when the timer runs out, and so I don't see the desktop notification. I would like to request a feature that would allow me to select an audible tone to match the desktop notification. If I could have anything I wanted, I'd like the option to tie the audible tone into the audio theme currently selected on my account.

Regardless, it's an awesome little extension, and I appreciate your work.

**Comment by ofekmiz** [comment]
Hi! sound notifications were added in version 5.1 ! (TODAY) , there is only one sound, I might add more sound in the future
