### ISSUE TITLE
Pay to pass not working 

### ISSUE THREAD

**Issue by immattao** [ofekmiz/Habitica-Pomodoro-SiteKeeper#113]
**Browser**: Microsoft Edge
**Problem**: After clicking "Pay to pass", the website reloads and asking "Pay to pass" again. Coin is not reduced. Encounter this when not being in a pomodoro session.
**Example**:

Setting
<img width="380" alt="image" src="https://user-images.githubusercontent.com/71063988/209294812-f1b1bd5b-bfe9-44a9-a889-661fbcedf9f8.png">

When visit site
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/71063988/209294137-0bfa3aae-4881-4b35-bea4-fd31699be003.png">

After clicking "Pay to pass", the webpage reloads
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/71063988/209294271-2664f759-cf80-4e91-87cb-c30fd27b1965.png">

And then... nothing changed!
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/71063988/209294479-d4a1df2d-de71-45df-812e-073f09f7ca68.png">
<img width="404" alt="image" src="https://user-images.githubusercontent.com/71063988/209294521-d30378e2-a14a-437a-ac16-6a52fc856f7c.png">

**Comment by ofekmiz** [comment]
Hi, it might be a connection issue with Habitica.

1. Click on settings>habitica
2. Make sure the user name and api token are correct
3. Click save

Let me know if this works for you.

**Comment by immattao** [comment]
Hi thanks for the reply.

Actually I just got it fixed by restarting the browser (should have done
this before posting an issue lol). My Habitica had already connected before
the error occurred.
