### ISSUE TITLE
Question: can I change habit and reward names? 

### ISSUE THREAD

**Issue by writeblankspace** [ofekmiz/Habitica-Pomodoro-SiteKeeper#116]
If I do, will the extension break / make new ones and ignore the og one?

**Comment by ofekmiz** [comment]
Hi, please do not change the names of the rewards and habits created by the
extension, it might cause some issues with the connection to Habitica

**Comment by writeblankspace** [comment]
ok, thanks!

**Comment by Akszyn** [comment]
Is the default reward is 0 is there just something wrong with me?

**Comment by ofekmiz** [comment]
Hi, if you mean the cost of the reward than yes.
The cost changes automatically according to the blocked website cost
