### ISSUE TITLE
New tab (which are blocked) appeared randomly

### ISSUE THREAD

**Issue by Htminhduc** [ofekmiz/Habitica-Pomodoro-SiteKeeper#12]
The situation is: I opened Reddit, I saw the pay to pass site (which is intended), I did't want to waste money then so I closed the tab. 
Here is the bug: Reddit randomly appeared out of nowhere after some time. As I was doing other shit, Reddit appeared (and the pay to pass site too) and it continued until I pay.

**Comment by ofekmiz** [comment]
Hi, This bug is supposed to be fixed in version 5.1, is this the version you are using (it was published today)

**Comment by Htminhduc** [comment]
Okay, you worked hard, thank you for your work.

**Comment by ofekmiz** [comment]
Sure, thanks for the feedback. Let me know if the bug is fixed :)

**Comment by Htminhduc** [comment]
It is good now=)
