### ISSUE TITLE
The button to block websites or edit already blocked sites is not visible

### ISSUE THREAD

**Issue by Fhelyp** [ofekmiz/Habitica-Pomodoro-SiteKeeper#126]
After adding a website to the blocklist, the corresponding button is no longer available on other pages. Also, I can't remove the blocked site or edit the set values. I didn't find this option on the other screens of the modal.

![image](https://github.com/ofekmiz/Habitica-Pomodoro-SiteKeeper/assets/76003427/518bbbee-604d-41ce-b26d-88cdb0bb7f0b)

**Comment by ofekmiz** [comment]
Hi! please check that the "Hide edit options" is not checked
![2024-02-21_20h45_13](https://github.com/ofekmiz/Habitica-Pomodoro-SiteKeeper/assets/39601942/f68f65a8-ac88-4bcf-a577-6378900f8420)

**Comment by Fhelyp** [comment]
OMG, you're right, this option was checked. It worked! Sorry for the unnecessary ticket!

And thanks for the awesome plugin!
