### ISSUE TITLE
Unwanted and Unticipated Mutes from all Sites when "mute blocked sites" feature is on

### ISSUE THREAD

**Issue by Kaizen543** [ofekmiz/Habitica-Pomodoro-SiteKeeper#15]
I troubleshooted it on my own and found out that even paid blocked websites goes muted by themselves. After a while.

Another thing is that even non-blocked websites mutes themselves when a "_blocked website_" tab has been paid and opened.

I think the reason is from the code of the mute feature. One of the best feature but not polished and ready for use just yet.

TLDR; websites gets muted as if someone is muting them after leaving the tab for 5 secs. regardless if its not in the block list

**Comment by ofekmiz** [comment]
@Kaizen543 Should be fixed now :) let me know how it works for you.

**Comment by Kaizen543** [comment]
It works perfectly. If no update after 4 days of use consider it fixed. 🥇
