### ISSUE TITLE
Simultaneous Multiple Pay to Pass Overlay 

### ISSUE THREAD

**Issue by Kaizen543** [ofekmiz/Habitica-Pomodoro-SiteKeeper#17]
[2020-08-30 04-57-14.zip](https://github.com/ofekmiz/Habitica-Pomodoro-SiteKeeper/files/5145986/2020-08-30.04-57-14.zip)

**Comment by Kaizen543** [comment]
Screen Recording included above

**Comment by ofekmiz** [comment]
Thanks for the recording!
So I have good news and bad news.

The bad news:
It is indeed a bug, not sure why it happens yet, probably delayed communication with Habitica.

The good news:
if you will check your gold amount Habitica you will see that if the site is still blocked it means you werent charged! so no worries, if this happens simply try a few more times to click on "pay to pass", it should only charge you once when it removes the block.

I'm working on a fix :)

**Comment by Kaizen543** [comment]
I knew it. I have a feeling that it doesnt recharge gold but just failed to apply the payment. I can live with that, thank you.
    On Sunday, 30 August 2020, 05:41:05 am GMT+8, OfeX <notifications@github.com> wrote:  
 
 


Thanks for the recording!
So I have good news and bad news.

The bad news:
It is indeed a bug, not sure why it happens yet, probably delayed communication with Habitica.

The good news:
if you will check your gold amount Habitica you will see that if the site is still blocked it means you werent charged! so no worries, if this happens simply try a few more times to click on "pay to pass", it should only charge you once when it removes the block.

I'm working on a fix :)

**Comment by ofekmiz** [comment]
@Kaizen543 
Just uploaded a new version 5.2 with Habitica communication improvments. 
Let me know how it works for you
