### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by paglias** [ofekmiz/Habitica-Pomodoro-SiteKeeper#18]
Hi, I'm Matteo (paglias) from the Habitica team, I'm opening this issue because our logs are showing that this extension is having a lot of requests blocked due to exceeding the rate limits we have added a few months ago for the API. They're explained here https://habitica.fandom.com/wiki/Guidance_for_Comrades#Rate_Limiting 

Let me know if you have any question or need help fixing the issue :)

**Comment by ofekmiz** [comment]
Thanks @paglias  , I just uploaded a new version that should lower the rate. Please let me know if it persists.

**Comment by paglias** [comment]
@ofekmiz there are still some limits being hit with the `GET /api/v3/user` route but I'm not sure if all users are using the updated version of the extension or not

**Comment by paglias** [comment]
For example there's an user that in 10 minutes triggered the rate limits 1900 times so that would be more than 2000 requests to that url in 10 minutes

**Comment by ofekmiz** [comment]
@paglias , I uploaded another version that should improve the rate. 
Is there a way for me to get access the Habitica logs regarding the extension? maybe by automatic daily email or something like that?
Thanks :)

**Comment by paglias** [comment]
@ofekmiz thanks! Looks like the rate limits are not being hit anymore by the extension.

Unfortunately sharing the logs is not something that I can do, but in this case they're simply the HTTP error responses being sent to client so you could add yourself a logging library to the extension and use it to log every time an AJAX request results in an error. 

Internally we use [Loggly](https://www.loggly.com/) which has a free tier that you can use, but there are plenty of other service providers around

**Comment by ofekmiz** [comment]
Great! Thanks
