### ISSUE TITLE
Blocking Google.com creates infinite loop of redirects

### ISSUE THREAD

**Issue by StephenHnilica** [ofekmiz/Habitica-Pomodoro-SiteKeeper#2]
Blocking Google.com creates a redirect loop when hitting "cancel" in the dialog box.

If you don't have enough coins, it creates an infinite loop of redirects.

Perhaps have an "advanced setting" to set a custom re-direct, or setting the redirect to Habitica or "new tab" might fix this issue.

**Comment by ofekmiz** [comment]
Thanks for the report

**Comment by ofekmiz** [comment]
Fixed!
replaced redirect with website overlay
