### ISSUE TITLE
Notification sounds

### ISSUE THREAD

**Issue by GaviLazan** [ofekmiz/Habitica-Pomodoro-SiteKeeper#20]
Could you allow for custom notification sounds? The trumpet is startling and loud, and I would much prefer a chime or something calm

**Comment by GaviLazan** [comment]
A couple of ideas:

https://freesound.org/people/jgreer/sounds/333629/
https://freesound.org/people/steffcaffrey/sounds/449946/
https://freesound.org/people/schreibsel/sounds/539915/
https://freesound.org/people/wormletter/sounds/513865/
https://freesound.org/people/SamuelGremaud/sounds/517661/

**Comment by ofekmiz** [comment]
Sure :) will be added soon

**Comment by ofekmiz** [comment]
@GaviLazan Added sounds to the new update, will be available soon!

**Comment by GaviLazan** [comment]
Love the new sounds. Thanks!
