### ISSUE TITLE
control panel blocking timer interface

### ISSUE THREAD

**Issue by yougnut** [ofekmiz/Habitica-Pomodoro-SiteKeeper#21]
![image](https://user-images.githubusercontent.com/67062125/96715000-91cc9e00-13d5-11eb-9120-c7f0b93eb3ec.png)
As shown in the screenshot, the control panel in the new update blocks the upper portion of the timer interface, otherwise its overall a great update, hope you keep up the great work :)

**Comment by ofekmiz** [comment]
Hi :)
What browser version are you using?
Can you give me some other screenshots, maybe we can find more issues like that...
This is how it should look:
![image](https://user-images.githubusercontent.com/39601942/96728124-7739fb00-13bc-11eb-8070-6a520eb2edd8.png)
![image](https://user-images.githubusercontent.com/39601942/96728174-828d2680-13bc-11eb-839d-92d506520b1a.png)

Thanks!

**Comment by ofekmiz** [comment]
Try changing Chromes font size settings:
1. Go to chrome://settings/fonts?search=font
2. set the minimum font size to 7
![Uploading image.png…]()

**Comment by ofekmiz** [comment]
@yougnut 
Try changing Chromes font size settings:

Go to chrome://settings/fonts?search=font
set the minimum font size to 7
![image](https://user-images.githubusercontent.com/39601942/96731174-a4d47380-13bf-11eb-87b0-a959d9e9fb8e.png)

**Comment by yougnut** [comment]
Oh thanks a lot, didn't realize it depends on browser font size :D
