### ISSUE TITLE
"Hisory" tab?

### ISSUE THREAD

**Issue by LoquaciousLynx** [ofekmiz/Habitica-Pomodoro-SiteKeeper#25]
Just a small thing I noticed: There is a tab titled "Hisory" which seems like it is a typo of "History". Not like it changes anything usage-wise one way or another, but I thought it might be good to bring it up.

![Screen Shot 2020-10-22 at 2 20 22 PM](https://user-images.githubusercontent.com/67295371/96931472-38667c80-1472-11eb-91d0-b45ff2020642.png)

**Comment by ofekmiz** [comment]
Thanks :)
