### ISSUE TITLE
Break Extension Ticker

### ISSUE THREAD

**Issue by MrsKatUSMC** [ofekmiz/Habitica-Pomodoro-SiteKeeper#26]
Right now there is a "Clock Ticking Sound" option that just ticks 24/7.... it just grates on my nerves when I'm working or on break, so I keep it off.

Can you make an option that makes that ticking sound only happen during the "break extension", to audibly remind us to Start the next Pomodoro sooner than later.

**Comment by ofekmiz** [comment]
FYI , Some people like to work with an ambient sound like a ticking clock on the background , that's what the option is used for :)

**Comment by MrsKatUSMC** [comment]
That is soo nice!  I see myself using the new bird & cricket tones frequently!

**Comment by ofekmiz** [comment]
Glad you like it :)
