### ISSUE TITLE
Working hours mod

### ISSUE THREAD

**Issue by Melistraza** [ofekmiz/Habitica-Pomodoro-SiteKeeper#27]
I use same laptop  for work and for personal needs.
And to use my laptop after work I need turn off extension.
Also I have second PC with same Google account and I use it only for personal need so I also need turn off extension some how!

So it would be great to make working hours schedule or some button to turn off extension till tomorrow!

**Comment by ofekmiz** [comment]
Hi @Melistraza 
There is no schedule option and unfortunately, it is not that simple to implement. I do think about adding it in the future but currently, history stats are a higher priority. On the other hand, there is a **Vacation Mode** that allows you to free pass all websites :). You can find the option under Settings > Blocker.
Hope it helps!

**Comment by Melistraza** [comment]
@ofekmiz 100 percent agree with you that it is overhead creating working schedule!!!
Good option will be keeping Vocation mode status in browser locally it will helps to separate workstation.
And keep this setting in more handy place.

**Comment by ofekmiz** [comment]
I can make it saved locally, or maybe even set a time when it auto triggers (without date), what would be better?  
About keeping the setting in a more handy place... many users asked for the opposite because it was tempting to "cheat" that way, so I moved it.

**Comment by ofekmiz** [comment]
@Melistraza I can make it saved locally, or maybe even set a time when it auto triggers (without date), what would be better?
About keeping the setting in a more handy place... many users asked for the opposite because it was tempting to "cheat" that way, so I moved it.

**Comment by ofekmiz** [comment]
I had some free time, so... I decided to make it happen :)
 A **working schedule** will be available in the next update! 🎉
![image](https://user-images.githubusercontent.com/39601942/97498861-98c75380-1975-11eb-9f39-a219cf84844f.png)

**Comment by Melistraza** [comment]
extremely fast feature development )
Thanks!
