### ISSUE TITLE
History data survey 🙋‍♂️📊

### ISSUE THREAD

**Issue by ofekmiz** [ofekmiz/Habitica-Pomodoro-SiteKeeper#29]
Hi everyone! 
Let me know in the comments what kind of data/graphs would you like to see in the "History" section. 
You can also send suggestions to ofex.create@gmail.com

If you find a suggestion you like, please give a 👍 to vote for it.

**Comment by yshyonli2** [comment]
Hey! Here are my suggestions:
- Average number of Pomodoros per day
- Lifetime number of Pomodoros
- Lifetime number of Pomodoros, grouped by day of the week
- Lifetime number of Pomodoros, grouped by date (similar to GitHub’s contributions graphic on user profile pages)

In any case, thank you so much for working on this extension. I left a rather lengthy review for your extension on the Chrome Web Store a month ago with a number of feature suggestions, and I’ve been taken aback at the sheer speed at which you’ve been implementing them. I mean, I think the recent changes have pretty much covered the whole list. Just wow.

So, with that in mind, thanks again, and remember to take care of yourself. :) (I’ve also updated my review from four to five stars.)

**Comment by RW21** [comment]
Hey, I really like the new update.

Few suggestions.
- Weekly stat which shows the number of pomodoros per day.
    - (Lifetime average stats might not work because I don't use pomodoro everyday)
- Monthly stat showing pomodoros for each day.
   - Something like a calender view.
- I really like @yshyonli2 's suggestion of  
   - > Lifetime number of Pomodoros, grouped by date (similar to GitHub’s contributions graphic on user profile pages)
   - Would be really cool to see something like github profile page. 

I'm not sure if there are limitations on how back you can go back in history with the current api. If these stats are only being stored locally, it would be great if there is way to get a backup of them in csv or something.

**Comment by ofekmiz** [comment]
Hi @yshyonli2 @RW21 , Thanks for the suggestions :)
The next update has a "GitHub" view for 1 year. Click on Full History to see it!
![image](https://user-images.githubusercontent.com/39601942/97856327-cceb9d00-1d04-11eb-95eb-6fb7eccf7b3b.png)

**Comment by RW21** [comment]
@ofekmiz 
That was quick 😄 . Thanks for the features! 

Just a small feedback: I think a bar graph instead of a pie chart is better at representing the total pomodors by week day. Its kind of awkward comparing each day in a circle.

**Comment by ofekmiz** [comment]
@RW21 Lol, I actually like the pie chart, it shows the total Pomodoros by weekday for **All Time**, not just this week. It helps to recognize your most productive days even when you are not aware of that.  Above the pie chart, there is also a bar graph with the last 7 days stats, and you can move forward or backward on the timeline.
