### ISSUE TITLE
Keyboard shortcut to resume pomodoro from break

### ISSUE THREAD

**Issue by RW21** [ofekmiz/Habitica-Pomodoro-SiteKeeper#30]
## Feature request

Sometimes I find it tedious to click on the extension and start my pomodoro from a break. 
I think a customisable keyboard shortcut to start pomodoros would be great.

**Comment by ofekmiz** [comment]
@RW21 Done! 
Default hotKey is **Alt+Shift+P**
To change the hotkey go to **chrome://extensions/shortcuts**.

Will be available in the next update :)

**Comment by RW21** [comment]
@ofekmiz Very nice! Thanks!
