### ISSUE TITLE
Suggestion: Lower ambient sound volume Issue: sound overlaps

### ISSUE THREAD

**Issue by trojanwars** [ofekmiz/Habitica-Pomodoro-SiteKeeper#34]
Hello, first of all i'd like to thank you for this amazing extension! I dont usually stick to pomodoro timers but ever since i linked it to my habitica account it has been more fun and rewarding. 
I love the ambient sound feature, it helps me focus.  I like using your built-in sounds as it automatically stops when the timer stops. My only issue is: it is rather loud. **The lowest volume option is not ideally low;** 
I hope that doesn't sound very nit-picky, but the loud volume can be disorienting while in deep focus. 
Now onto the _issue_: when changing ambient sounds, sometime the **sounds will overlap** and keep playing, and the only way i can stop it is closing my browser. 
Everything else is perfect, thank you!

**Comment by ofekmiz** [comment]
Thanks for the feedback :), the bug is fixed and will be added in the next update with more sensitive volume control.
