### ISSUE TITLE
Feature Request: UI element to set serverUrl (for a local Habitica instance)

### ISSUE THREAD

**Issue by swilliams-dev** [ofekmiz/Habitica-Pomodoro-SiteKeeper#36]
Currently we must modify the serverUrl in SitePass/app/background.js manually every update, or redirect via DNS. Ideally, we would have an area in settings we could enter in our local address.

**Comment by swilliams-dev** [comment]
Also opened upstream: https://github.com/MHDante/Habitica-SitePass/issues/13

**Comment by ofekmiz** [comment]
Hi, I'm not sure if I understand.... Can you explain what do you mean by "serverUrl in SitePass/app/background.js". Also there is no redirect DNS in this extension (unlike MHDante's extension) - I replace the redirect to google with a website overlay.

Thanks

**Comment by ofekmiz** [comment]
@swilliams-dev  Hi, I'm not sure if I understand.... Can you explain what do you mean by "serverUrl in SitePass/app/background.js". Also there is no redirect DNS in this extension (unlike MHDante's extension) - I replace the redirect to google with a website overlay.

Thanks

**Comment by ofekmiz** [comment]
If you mean to change the Habitica serverUrl for the API, it would be great if you explain in details what do you need for this to work. I never used Habitica locally but if you explain exactly what is needed I can add this feature :)

**Comment by swilliams-dev** [comment]
I think just an easy option to modify the serverUrl should do it, it is for this setup:
https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Docker

**Comment by swilliams-dev** [comment]
You may find some benift from the ability to test via local api...
https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API
Should just require setting here... I could fork and rebuild, but this would be better to be a user definable var: https://github.com/ofekmiz/Habitica-Pomodoro-SiteKeeper/blob/master/SitePass/app/background.js#L4

**Comment by ofekmiz** [comment]
@swilliams-dev Sorry for the delay.  It's a simple feature but I have other priorities for now. Thank you for your patient!

**Comment by ofekmiz** [comment]
@swilliams-dev any update? :)

**Comment by swilliams-dev** [comment]
Apologies, I'm out of town currently, but will be back by end of month. Thanks for implementing,  I'll be sure to test asap :)

**Comment by ofekmiz** [comment]
@swilliams-dev any updates? :)

**Comment by swilliams-dev** [comment]
Sorry for the insane levels of delay... I just got it up in docker and can test it out. How do I build/install this from your fork @ofekmiz?

**Comment by bootymcjudy** [comment]
I just tested this on my own local install and it works! Using version 6.1.2 on Firefox
You need to append /api/v3/ to the end of the url.
Since I also did it on my local machine the url I used,
`http://localhost:8080/api/v3/`
