### ISSUE TITLE
Always shows 0/4 Pomodoro, and never comes long pause

### ISSUE THREAD

**Issue by clecthiago** [ofekmiz/Habitica-Pomodoro-SiteKeeper#38]
Hi, I'm having issues when finishing a pomodoro.
Fisrt i go to my extension to start manually, and see a tomato in a bluebackground with a info 0/4 pomodoros (appears normal for me ).
So, I start my first (clicking on the tomato guy with a play button) and see the tomato sleeping with a a green background (and showing 0/4 yet - sounds normal again).
The time goes on until the notification appears
I go to the extension, see a "good" message with  a 1/4 in a green-background again. 
Until here (for me) totally good.

Maybe the problem comes at next step (I'll call it by Step B).
Here on next screen, I can click on 'x' to escape this screen (looks the correct way to go to my short pause), or clicking on tomato saying 'Zzz' to go to focus-mode (hover the tomato guy, looks the way to ignore pause).

If I press on 'x', I go to the bluebackground and stat with a 0/4, but tomato-guy says +1.
Otherwise, If I press on the "tomato wants to sleep" (to to foccus - I suppose), appear to me a blue-background . At this point i dont know if I go to short pause or focus mode, and my conffusion comes because I see a bluescreen again and a tomato sleeping. This screens (and tomato) is very like a foccus mode, but time is short, so very confuse to me here. 
After this I receive a Alert with a "go to work" and a red background.

The red screen with a tomato warning and a countdown appears a delay to go back to work.
After the red screen I go back to the bluescreen with a **0/4**, and a tomato saying +1

My problem is: the info 0/4 always is present and never goes out, so a Inever go to my long pause.

Am I doing something wrong ?

Whats the meaning of the 'x' button at Step B (mentioned above) ?

The "tomato guy" is counting my pomodoros , but i dont know if in the right way.

I'm start using  the pomodoro only, not the site-blocker.

**Comment by ofekmiz** [comment]
@clecthiago Hi :)
Pressing the "x" means "quit" and it resets the pomodoro. To use the app as intended, there is only one button you need and it's the tomato character.

Here is the workflow:
![image](https://user-images.githubusercontent.com/39601942/103932174-1ce24800-512a-11eb-9c38-fdf2e6edd875.png)

Let me know if it's clear enough!

**Comment by clecthiago** [comment]
Thank you @ofekmiz,
I was doing a error on my configuration and having confusion with the red background (break extension).

I was thinking that the red background (break extension) needed to go to 0 seconds, but in fact I need to avoid it, going fast when this clock starts.

I was using a configuration (in the 'timer-tab' that was making  the break extension works not properly.
I was Trying to simulate here and I didnt get the error again.

My problem was Solved, but I want to ask a improvement and dont know how to do it.

I'm using normally (and loving it, btw), but I want to know if is it possible to do a little modification with these backgrouds themes. I mean, just change the color of Active mode and short-pause (or even long-pause) mode ?

I need to do something on this issue ? Open another ?

**Comment by ofekmiz** [comment]
@clecthiago If you can open a new topic with all the detail I would greatly appreciate it :)
