### ISSUE TITLE
Quick Glance Visual Representation of Amount of Time Remaining

### ISSUE THREAD

**Issue by tripwalks** [ofekmiz/Habitica-Pomodoro-SiteKeeper#43]
It would be cool if there was an option to quickly glance and see amount of time remaining on toolbar related to break. I love the time option on it though. However, for me its less important the exact minutes and seconds

**Comment by ofekmiz** [comment]
Hi, I'm not sure what do you mean by that. You can see the remaining time on the extension icon 
![image](https://user-images.githubusercontent.com/39601942/107478899-e9f4ff00-6b82-11eb-82db-694a92e2d826.png)
