### ISSUE TITLE
Feature Request: Toggle to allow sitekeeper sites to use during a pomo

### ISSUE THREAD

**Issue by ZackaryW** [ofekmiz/Habitica-Pomodoro-SiteKeeper#44]
Toggle to allow sitekeeper sites to use during a pomo

**Comment by ofekmiz** [comment]
Hi there! I'm not sure what do you mean by that?
If you want to whitelist a specific url you can do it here:
![image](https://user-images.githubusercontent.com/39601942/112196845-1dac5580-8c14-11eb-8ceb-5d813e2217f6.png)

If you want to allow all websites to be free during pomo break you can do it here:
![image](https://user-images.githubusercontent.com/39601942/112197004-47fe1300-8c14-11eb-847d-d4eb3caadee8.png)

Or you can simply activate "vacation mode" to make all websites free on toggle:
![image](https://user-images.githubusercontent.com/39601942/112197147-6e23b300-8c14-11eb-9e63-a41d86789d49.png)

Let me know if it helps :)

**Comment by ofekmiz** [comment]
Hi @ZackaryW, can I close this issue or would you like anything else?
