### ISSUE TITLE
Can't Block Sites

### ISSUE THREAD

**Issue by byohub** [ofekmiz/Habitica-Pomodoro-SiteKeeper#48]
I'm looking at the "Navigate to the sites you want to block during Pomodoro and click on 'Block Site'." screen, but there's no block site button, what do?

**Comment by ofekmiz** [comment]
Hi @byohub , to block a website navigate to it  in the browser and click here:
![image](https://user-images.githubusercontent.com/39601942/112766499-c135a580-901a-11eb-9ee9-87511084eeb2.png)

If the button is missing please provide a screenshot

Please let me know it worked out for you :)

**Comment by byohub** [comment]
![Screenshot 2021-03-28 171800](https://user-images.githubusercontent.com/81390584/112769948-a0a12780-8fe9-11eb-82ac-c6eb64f5f64f.jpg)

This is the problem

**Comment by ofekmiz** [comment]
@byohub this seems like a bug, what website are you trying to block?

**Comment by byohub** [comment]
I tried on many sites none worked, but reinstalling worked

**Comment by ofekmiz** [comment]
Great! Thanks for the update.
