### ISSUE TITLE
[🦁 Brave Browser] Preferences Not Saved and Block Not Initially Starting

### ISSUE THREAD

**Issue by cpustejovsky** [ofekmiz/Habitica-Pomodoro-SiteKeeper#49]
On Brave browser, the pomodoro timer does not seem to work until I go into my settings and change something, then the block screen will appear.

Also, I have to manually set my settings to count a pomodoro on my Habitica account. 

This seems to happen when I restart my machine. I am on Ubuntu 20.04.

I will continue to add comments with more information is that would be helpful.

**Comment by ofekmiz** [comment]
Thanks! I still haven't really tested in a Brave browser so any piece of information would be very helpful

**Comment by cpustejovsky** [comment]
Yes, apologies
