### ISSUE TITLE
Can't Pay to Pass 

### ISSUE THREAD

**Issue by byohub** [ofekmiz/Habitica-Pomodoro-SiteKeeper#50]
Every time I click "pay to pass" the site reloads and the "pay to pass" option comes up again without taking the habitica coins. The first time it happened an error message, though I forget the message all help is appreciated.

**Comment by ofekmiz** [comment]
Hi @byohub , sometime this happens due to connection problems with Habitica. make sure you can log in to you habbitica account and try to enter your Habitica User ID and API Token in the settings again. Don't forget to click save.

![image](https://user-images.githubusercontent.com/39601942/113381937-ec0c5a80-9388-11eb-91b3-4111322192bd.png)

**Comment by byohub** [comment]
Just tried this and it didn't seem to work

**Comment by ofekmiz** [comment]
@byohub what browser are you using? And if you can send a screen recording with the error it would really help.

**Comment by byohub** [comment]
https://user-images.githubusercontent.com/81390584/113521886-02214300-9562-11eb-9ddf-0d5f8032c6b7.mp4

**Comment by byohub** [comment]
https://user-images.githubusercontent.com/81390584/113521940-6d6b1500-9562-11eb-9fe0-0d641c6f7b3a.mp4
I use google and this happen on every blocked site.

**Comment by ofekmiz** [comment]
@byohub 
Do you have a time indicator like in this recording?: [https://ttprivatenew.s3.amazonaws.com/pulse/ofekm/attachments/16447698/TinyTake05-04-2021-02-08-03.mp4 ](https://ttprivatenew.s3.amazonaws.com/pulse/ofekm/attachments/16447698/TinyTake05-04-2021-02-08-03.mp4 ) 

Do you see a reward in habitica called "Site Pass" like this:
![image](https://user-images.githubusercontent.com/39601942/113523980-49d0ba80-95b4-11eb-951b-231c8409eb78.png)

Do you still get any errors?

If all seems fine try to reinstall the extension, make sure to backup your history before you do that.

Let me know if it worked.
thanks

**Comment by byohub** [comment]
No haven’t s seen the timer's indicator for websites since it stopped working
I don't see a reward like that I might have deleted it, anyway to get it back?
No I only got the error message the first time it didn't work

**Comment by ofekmiz** [comment]
@byohub The pay to pass won't work without the "Site Pass" reward in Habitica.
Try the following steps and in each step check if the "Site pass" reward is back in habitica:

1. Try to disable and enable the Habitica connection here:
![image](https://user-images.githubusercontent.com/39601942/113576910-111ef880-9629-11eb-983f-676dfb71fdb2.png)

2. Back up your Pomodoro history here:
![image](https://user-images.githubusercontent.com/39601942/113577114-6bb85480-9629-11eb-942f-a5cb05851eae.png)

And then:
2. Try to disable and enable the extension in chrome://extensions/
![image](https://user-images.githubusercontent.com/39601942/113577015-3f043d00-9629-11eb-8ba5-91eb5456437d.png)

3. Try to uninstall and install the extension here https://chrome.google.com/webstore/detail/habitica-pomodoro-sitekee/iaanigfbldakklgdfcnbjonbehpbpecl

**Comment by byohub** [comment]
Disable then enable in extensions worked! Thank you for your help!!
