### ISSUE TITLE
New Feature - Finish pomodoro early

### ISSUE THREAD

**Issue by MrKebab362** [ofekmiz/Habitica-Pomodoro-SiteKeeper#55]
When we finish our work early before the timer ends, but don't want to lost hp because we didn't quit or skip, we just finished work early

**Comment by ofekmiz** [comment]
Thanks, for now there is a skip option in the setting, but you won't get gold and xp for skipping. I will add it in the future!

![image](https://user-images.githubusercontent.com/39601942/114291798-d25ac980-9a92-11eb-83b4-026bb80df376.png)
![image](https://user-images.githubusercontent.com/39601942/114291804-f3231f00-9a92-11eb-8322-0e02f096f932.png)

**Comment by MrKebab362** [comment]
Actually you might as well put this on low priority, because even if I finish a piece of work, I should still find other productive things to do during the timer
