### ISSUE TITLE
Credential error! The extension is currently not updating Habitica! (Opera users)

### ISSUE THREAD

**Issue by MechanicalElf** [ofekmiz/Habitica-Pomodoro-SiteKeeper#6]
MacOS 10.14.3, Opera 66.0.3515.103

**Issue**: When I try to enter my Habitica creds into the SiteKeeper extension I get the following error message:
`Credential error! The extension is currently not updating Habitica!`
![image](https://user-images.githubusercontent.com/61316618/75033728-36e44f00-54b4-11ea-811e-51f11764d3ac.png)

The SiteKeeper extension works perfectly on my Windows 10/Opera rig, and the settings, User ID & API key are identical. I have an Opera extension that allows Chrome extensions to work in Opera.

**Troubleshooting**: Logged out/in to Habitica, uninstalled/re-installed extension

**Comment by ofekmiz** [comment]
Hi, thanks for the feedback :)
I never tried the extension on Opera. Can you send a link to the Opera extension that you use to allow Chrome extensions? I'll need to see it for myself. 
Thanks

**Comment by MechanicalElf** [comment]
Sure, and thanks for looking into this!
https://addons.opera.com/en-gb/extensions/details/install-chrome-extensions/

**Comment by ofekmiz** [comment]
Hi, I fixed some bugs lately, is it still happening?

**Comment by ofekmiz** [comment]
The issue is fixed.
Please make sure you use this extension for Opera:
https://addons.opera.com/he/extensions/details/install-chrome-extensions/
