### ISSUE TITLE
[Edge Dev Browser] Extension Icon Timer Is Blocked / Occluded / Imcomplete

### ISSUE THREAD

**Issue by WongZeHao** [ofekmiz/Habitica-Pomodoro-SiteKeeper#67]
Hi, 

The icon's timer is not completely rendered or blocked as shown in the following image.
![image](https://user-images.githubusercontent.com/51298903/120880739-ae34e800-c5fe-11eb-9f01-ca57c4e08d4f.png)

I do not face this issue when I am using the Brave browser (on another laptop). 

Here are the details of my browser:
Microsoft Edge
Version 92.0.902.4 (Official build) dev (64-bit)

**Comment by ofekmiz** [comment]
@WongZeHao Thanks for the feedback! I plan on releasing an official version for Edge and Firefox soon. Stay tuned :)

**Comment by ofekmiz** [comment]
@WongZeHao Thanks for the feedback. The edge version is now officially available! Check it out and let me know if it solves the issue for you. **Please don't forget to export your history before reinstalling**
