### ISSUE TITLE
Not incrementing pomodoro combo.

### ISSUE THREAD

**Issue by xsigmu06** [ofekmiz/Habitica-Pomodoro-SiteKeeper#7]
Heya,
recently i discovered a problem after the 25 minute countdown, in which my pomodoro sometimes bugs out like this:
![image](https://user-images.githubusercontent.com/60696576/77250336-a4b49f80-6c47-11ea-8396-e0e0045b7786.png)
To remedy it i have to click on another tab, which sometimes helps, other times i have to do that a couple of times. I'm using it as chrome extention, while having habitica open in another tab at all times.
Even if the UI works, my pomodoro combo is not adding up at all, not even in habitica.
Do you have an idea what might be causing this?
Thanks a lot so far i've been lovin it!

**Comment by xsigmu06** [comment]
![image](https://user-images.githubusercontent.com/60696576/77250524-d7ab6300-6c48-11ea-8e4a-e7deaacdf4c4.png)
For example here it says i did 3 pomodoros, but the combo counter stays at 0/4.

**Comment by ofekmiz** [comment]
Thanks! I'm working on a fix

**Comment by xsigmu06** [comment]
Update: So i observed that right after the countdown it actually counts up, and then after 10 or so seconds it goes blank like the 1st image i sent. After i switch tabs on browser, the GUI goes back to normal but the combo counter is already reset. Only thing that stays is normal pomodoro counter. Hope this helps.

**Comment by ofekmiz** [comment]
It helped a lot.  Thanks

**Comment by ofekmiz** [comment]
Hi, I just uploaded a fix in version 4.21.
It's now pending for google's review and will be available in the app store in a few days.
Please update the extension once the new version is available and let me know if the issue is fixed for you. 

Thanks!

**Comment by xsigmu06** [comment]
Great! I will update asap.

**Comment by xsigmu06** [comment]
So version 4.21 is up and so far it's working as it should! Good job! Thanks alot for making time for this.

**Comment by ofekmiz** [comment]
Thanks for the update :)
