### ISSUE TITLE
I have "NetworkError"

### ISSUE THREAD

**Issue by iseocruz** [ofekmiz/Habitica-Pomodoro-SiteKeeper#78]
I would like to report a bug. When I turn on my pc, a window show this message and its not count the pomodoro or the combos in habits habitica:

NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://habitica.com/api/v3/user/'.

Can you help me?

**Comment by ofekmiz** [comment]
@iseocruz Hi, please try to disable an re-enable the extension. 
- Right click on the extension icon and choose "manage extensions" 
![image](https://user-images.githubusercontent.com/39601942/138170727-264a3067-13ee-4d55-99d0-bdc449e829df.png)
-Disable and enable the extension
![image](https://user-images.githubusercontent.com/39601942/138170803-f717e911-5742-473f-9eec-4e1419d41051.png)

let me know if it solves the issue!
