### ISSUE TITLE
Transfer settings between browsers

### ISSUE THREAD

**Issue by DaRealBurnz** [ofekmiz/Habitica-Pomodoro-SiteKeeper#85]
Hi,

Sorry if this is the wrong place to ask this, but is it possible to transfer settings between browsers? I recently switched from Chrome to Firefox and was wondering if I can move everything across without having to set it all back up manually.

Any answer is much appreciated.
Thanks!

**Comment by ofekmiz** [comment]
@DaRealBurnz  Sure, 
go to history -> full history & backup -> download your data -> go to firefox and import the file
let me know if you need any help

**Comment by DaRealBurnz** [comment]
Hi @ofekmiz,

Thanks for the reply. I tried that and it worked, but it only seems to transfer the history and not other settings like sites to block. Is this intentional?

Thanks!

**Comment by ofekmiz** [comment]
Yes, sorry but you can only transfer the history data, the settings must be
done manually for now

**Comment by DaRealBurnz** [comment]
Ah, I see. Thanks for the help, and the great extension!
