### ISSUE TITLE
 total pomodoros for any month history

### ISSUE THREAD

**Issue by spexpion** [ofekmiz/Habitica-Pomodoro-SiteKeeper#88]
You should add total pomodoro time until now (in hours) for history logs + total pomodoros for any month

**Comment by ofekmiz** [comment]
Hi @spexpion ,
you can see the total pomodoros and hours until now in the history tab, and if you click on "Full history & backup" you can see a year view with total pomodoros for each month:
![image](https://user-images.githubusercontent.com/39601942/143171492-8857caa9-813e-4a3f-82a5-203ba4c3564b.png)
![image](https://user-images.githubusercontent.com/39601942/143172613-599c5e21-f05d-4e32-8371-2e65912264f8.png)
