### ISSUE TITLE
Credential error - no connection to habitica account

### ISSUE THREAD

**Issue by alautpetchknock** [ofekmiz/Habitica-Pomodoro-SiteKeeper#97]
![Screenshot_1](https://user-images.githubusercontent.com/99996777/154757743-f7322f7f-2a6d-4dbc-b79b-29a6c799ec14.png)

**Comment by alautpetchknock** [comment]
Account login info is correct but sadly its still not conencting with habitica :/

**Comment by ofekmiz** [comment]
Hi @alautpetchknock .
Please make sure you use the **user id** and not username (not@username). 
it can be found here: https://habitica.com/user/settings/api.

Let me know if it helps

**Comment by ofekmiz** [comment]
![image](https://user-images.githubusercontent.com/39601942/154764377-86672dcf-939b-47bf-b808-dea27f6840fe.png)

**Comment by alautpetchknock** [comment]
It worked!! Thanks a lot for the fast reply :))
Cheers!

**Comment by ofekmiz** [comment]
you're welcome :)
